### PR TITLE
PyJWT returns a string in version 2+

### PR DESCRIPTION
**Pull request by dalemyers**
Fixes https://github.com/microsoft/asconnect/issues/19

### CODE REVIEW

**Review by guojiubo — APPROVED** [review]

**Comment by dalemyers** [comment]
Btw, I figured it's not worth backporting this. We can consider it if it affects others. 

@guojiubo Can you do a release with this fix when you have time?

**Comment by guojiubo** [comment]
Sure.

**Comment by guojiubo** [comment]
@rchogan  sorry for the inconvenience, I'll release a new version today.

**Comment by guojiubo** [comment]
@rchogan  Released 2.2.12.

**Comment by rchogan** [comment]
Thanks @guojiubo!

**Pull request merged**
